# Generated by Django 2.1.7 on 2019-02-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pontos_turisticos', '0007_auto_20190216_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img_pontos_turisticos'),
        ),
    ]
